### ISSUE TITLE
src/test/deploy/pom.xml is not correct

### ISSUE THREAD

**Issue by hallywang** [eclipse-ee4j/glassfish-maven-embedded-plugin#16]
The xml node "configuration" should be under node "plugin",not under the "executions" node.

this is the correct pom:
```xml
<plugin>
                <groupId>org.glassfish.embedded</groupId>
                <artifactId>maven-embedded-glassfish-plugin</artifactId>
                <version>${project.version}</version>
                <configuration>
                    <app>test.war</app>
                    <port>8080</port>
                </configuration>
                <executions>
                    <execution>
                        <phase>install</phase>
                        <goals>
                            <goal>run</goal>
                            <goal>deploy</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

```

**Comment by pzygielo** [comment]
Please elaborate. I'm pretty sure the position of `configuration` in that `pom.xml` is correct.
Consult [POM Reference](https://maven.apache.org/pom.html).

**Comment by pzygielo** [comment]
Closing due to lack of response.

**Comment by arjantijms** [comment]
p.s. `mvn tidy:pom` ensures the correct preferential ordering is applied.

**Comment by dmatej** [comment]
Both variants are possible, both have consequences :-)
In this case it doesn't matter.

**Comment by pzygielo** [comment]
In fact for that particular plugin it does matter.

I didn't see it back in 2021, and forgot about that on closing.

But there is issue that I blame this plugin for. `run` goal reads plugin configuration directly and it doesn't feel right for me (but I don't remember details now).

**Comment by dmatej** [comment]
Hmm, we should fix it then ...

**Comment by pzygielo** [comment]
I proposed PR, to fix THIS issue. Configuration handling deserves separate one IMO.
